# Generated by Django 4.0.4 on 2022-05-27 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('car_model', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('year_of_manufacture', models.CharField(max_length=200)),
                ('fuel_tank_capacity', models.CharField(max_length=200)),
                ('engine_code', models.CharField(max_length=200)),
                ('mileage', models.CharField(max_length=200)),
                ('registration_date', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
