# Generated by Django 4.0.4 on 2022-05-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_cardata_car_model_remove_cardata_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardata',
            name='car_model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cardata',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cardata',
            name='engine_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cardata',
            name='fuel_tank_capacity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cardata',
            name='mileage',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cardata',
            name='registration_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cardata',
            name='year_of_manufacture',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
